---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: external-dns
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  dependsOn:
    - name: traefik
      namespace: traefik
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
    createNamespace: true
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: external-dns
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: external-dns
      interval: 12h
  values:
    image:
      registry: registry-1.docker.io
      repository: bitnamilegacy/external-dns
    
    provider: ovh
    policy: sync
    # txtOwnerId: argocd
    
    domainFilters:
      - glefer.fr
    
    sources:
      - ingress
    
    ingressClassFilters:
      - traefik
    
    ovh:
      endpoint: ovh-eu
      secretName: ovh-credentials
    
    logLevel: debug
    
    # Resources pour External DNS
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
    
    # Security context
    securityContext:
      capabilities:
        drop: [ALL]
      runAsNonRoot: true
      runAsUser: 65534
      readOnlyRootFilesystem: true
