---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 12h
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: grafana
      version: "7.0.19"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    adminPassword: aaa
    persistence:
      enabled: true
      size: 10Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - grafana.glefer.fr
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.glefer.fr
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring:9090
            access: proxy
            isDefault: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kubernetes-cluster-monitoring:
          gnetId: 15757
          revision: 37
          datasource: Prometheus
        kubernetes-cluster-summary:
          gnetId: 8588
          revision: 1
          datasource: Prometheus
        node-exporter:
          gnetId: 1860
          revision: 31
          datasource: Prometheus
        kubernetes-pods:
          gnetId: 15760
          revision: 16
          datasource: Prometheus
        nginx-prometheus-exporter:
          gnetId: 12708
          revision: 1
          datasource: Prometheus
        nginx-monitoring:
          json: |
            {
              "annotations": {
                "list": [
                  {
                    "builtIn": 1,
                    "datasource": "-- Grafana --",
                    "enable": true,
                    "hide": true,
                    "iconColor": "rgba(0, 211, 255, 1)",
                    "name": "Annotations & Alerts",
                    "target": {
                      "limit": 100,
                      "matchAny": false,
                      "tags": [],
                      "type": "dashboard"
                    },
                    "type": "dashboard"
                  }
                ]
              },
              "editable": true,
              "gnetId": null,
              "graphTooltip": 0,
              "id": null,
              "links": [],
              "panels": [
                {
                  "datasource": "Prometheus",
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "palette-classic"
                      },
                      "custom": {
                        "axisLabel": "",
                        "axisPlacement": "auto",
                        "barAlignment": 0,
                        "drawStyle": "line",
                        "fillOpacity": 10,
                        "gradientMode": "none",
                        "hideFrom": {
                          "legend": false,
                          "tooltip": false,
                          "vis": false
                        },
                        "lineInterpolation": "linear",
                        "lineWidth": 1,
                        "pointSize": 5,
                        "scaleDistribution": {
                          "type": "linear"
                        },
                        "showPoints": "never",
                        "spanNulls": false,
                        "stacking": {
                          "group": "A",
                          "mode": "none"
                        },
                        "thresholdsStyle": {
                          "mode": "off"
                        }
                      },
                      "mappings": [],
                      "thresholds": {
                        "mode": "absolute",
                        "steps": [
                          {
                            "color": "green",
                            "value": null
                          },
                          {
                            "color": "red",
                            "value": 80
                          }
                        ]
                      },
                      "unit": "reqps"
                    },
                    "overrides": []
                  },
                  "gridPos": {
                    "h": 8,
                    "w": 12,
                    "x": 0,
                    "y": 0
                  },
                  "id": 1,
                  "options": {
                    "legend": {
                      "calcs": [],
                      "displayMode": "list",
                      "placement": "bottom"
                    },
                    "tooltip": {
                      "mode": "single"
                    }
                  },
                  "targets": [
                    {
                      "expr": "rate(nginx_http_requests_total{namespace=\"glefer\"}[5m])",
                      "interval": "",
                      "legendFormat": "Request Rate - {{instance}}",
                      "refId": "A"
                    }
                  ],
                  "title": "NGINX Request Rate",
                  "type": "timeseries"
                },
                {
                  "datasource": "Prometheus",
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "thresholds"
                      },
                      "mappings": [],
                      "thresholds": {
                        "mode": "absolute",
                        "steps": [
                          {
                            "color": "red",
                            "value": null
                          },
                          {
                            "color": "green",
                            "value": 1
                          }
                        ]
                      }
                    },
                    "overrides": []
                  },
                  "gridPos": {
                    "h": 8,
                    "w": 6,
                    "x": 12,
                    "y": 0
                  },
                  "id": 2,
                  "options": {
                    "colorMode": "background",
                    "graphMode": "area",
                    "justifyMode": "auto",
                    "orientation": "auto",
                    "reduceOptions": {
                      "values": false,
                      "calcs": [
                        "lastNotNull"
                      ],
                      "fields": ""
                    },
                    "textMode": "auto"
                  },
                  "pluginVersion": "8.0.0",
                  "targets": [
                    {
                      "expr": "nginx_up{namespace=\"glefer\"}",
                      "interval": "",
                      "legendFormat": "NGINX Status",
                      "refId": "A"
                    }
                  ],
                  "title": "NGINX Status",
                  "type": "stat"
                },
                {
                  "datasource": "Prometheus",
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "palette-classic"
                      },
                      "custom": {
                        "axisLabel": "",
                        "axisPlacement": "auto",
                        "barAlignment": 0,
                        "drawStyle": "line",
                        "fillOpacity": 10,
                        "gradientMode": "none",
                        "hideFrom": {
                          "legend": false,
                          "tooltip": false,
                          "vis": false
                        },
                        "lineInterpolation": "linear",
                        "lineWidth": 1,
                        "pointSize": 5,
                        "scaleDistribution": {
                          "type": "linear"
                        },
                        "showPoints": "never",
                        "spanNulls": false,
                        "stacking": {
                          "group": "A",
                          "mode": "none"
                        },
                        "thresholdsStyle": {
                          "mode": "off"
                        }
                      },
                      "mappings": [],
                      "thresholds": {
                        "mode": "absolute",
                        "steps": [
                          {
                            "color": "green",
                            "value": null
                          },
                          {
                            "color": "red",
                            "value": 80
                          }
                        ]
                      },
                      "unit": "short"
                    },
                    "overrides": []
                  },
                  "gridPos": {
                    "h": 8,
                    "w": 18,
                    "x": 0,
                    "y": 8
                  },
                  "id": 3,
                  "options": {
                    "legend": {
                      "calcs": [],
                      "displayMode": "list",
                      "placement": "bottom"
                    },
                    "tooltip": {
                      "mode": "single"
                    }
                  },
                  "targets": [
                    {
                      "expr": "nginx_connections_active{namespace=\"glefer\"}",
                      "interval": "",
                      "legendFormat": "Active Connections - {{instance}}",
                      "refId": "A"
                    },
                    {
                      "expr": "nginx_connections_reading{namespace=\"glefer\"}",
                      "interval": "",
                      "legendFormat": "Reading - {{instance}}",
                      "refId": "B"
                    },
                    {
                      "expr": "nginx_connections_writing{namespace=\"glefer\"}",
                      "interval": "",
                      "legendFormat": "Writing - {{instance}}",
                      "refId": "C"
                    },
                    {
                      "expr": "nginx_connections_waiting{namespace=\"glefer\"}",
                      "interval": "",
                      "legendFormat": "Waiting - {{instance}}",
                      "refId": "D"
                    }
                  ],
                  "title": "NGINX Connections",
                  "type": "timeseries"
                },
                {
                  "datasource": "Prometheus",
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "thresholds"
                      },
                      "mappings": [],
                      "thresholds": {
                        "mode": "absolute",
                        "steps": [
                          {
                            "color": "green",
                            "value": null
                          }
                        ]
                      }
                    },
                    "overrides": []
                  },
                  "gridPos": {
                    "h": 4,
                    "w": 6,
                    "x": 18,
                    "y": 8
                  },
                  "id": 4,
                  "options": {
                    "colorMode": "value",
                    "graphMode": "area",
                    "justifyMode": "auto",
                    "orientation": "auto",
                    "reduceOptions": {
                      "values": false,
                      "calcs": [
                        "lastNotNull"
                      ],
                      "fields": ""
                    },
                    "textMode": "auto"
                  },
                  "pluginVersion": "8.0.0",
                  "targets": [
                    {
                      "expr": "nginx_connections_accepted{namespace=\"glefer\"}",
                      "interval": "",
                      "legendFormat": "Accepted",
                      "refId": "A"
                    }
                  ],
                  "title": "Total Accepted Connections",
                  "type": "stat"
                },
                {
                  "datasource": "Prometheus",
                  "fieldConfig": {
                    "defaults": {
                      "color": {
                        "mode": "thresholds"
                      },
                      "mappings": [],
                      "thresholds": {
                        "mode": "absolute",
                        "steps": [
                          {
                            "color": "green",
                            "value": null
                          }
                        ]
                      }
                    },
                    "overrides": []
                  },
                  "gridPos": {
                    "h": 4,
                    "w": 6,
                    "x": 18,
                    "y": 12
                  },
                  "id": 5,
                  "options": {
                    "colorMode": "value",
                    "graphMode": "area",
                    "justifyMode": "auto",
                    "orientation": "auto",
                    "reduceOptions": {
                      "values": false,
                      "calcs": [
                        "lastNotNull"
                      ],
                      "fields": ""
                    },
                    "textMode": "auto"
                  },
                  "pluginVersion": "8.0.0",
                  "targets": [
                    {
                      "expr": "nginx_http_requests_total{namespace=\"glefer\"}",
                      "interval": "",
                      "legendFormat": "Total Requests",
                      "refId": "A"
                    }
                  ],
                  "title": "Total HTTP Requests",
                  "type": "stat"
                }
              ],
              "refresh": "30s",
              "schemaVersion": 27,
              "style": "dark",
              "tags": [
                "nginx"
              ],
              "templating": {
                "list": []
              },
              "time": {
                "from": "now-1h",
                "to": "now"
              },
              "timepicker": {},
              "timezone": "",
              "title": "NGINX Monitoring - Glefer",
              "uid": "nginx-glefer",
              "version": 1
            }
    serviceMonitor:
      enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
