apiVersion: v1
kind: Namespace
metadata:
  name: loki
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-loki
  namespace: loki
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 12h
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: loki
      version: "5.47.2"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: loki
      interval: 12h
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
    test:
      enabled: false
    monitoring:
      serviceMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack
    gateway:
      enabled: false
