---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: loki
spec:
  interval: 12h
  install:
    createNamespace: false
  chart:
    spec:
      chart: promtail
      version: "6.15.5"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: loki
      interval: 12h

  values:
    config:
      clients:
        - url: http://loki:3100/loki/api/v1/push

      # 🟣 Pipelines appliquées à TOUS les scrape jobs
      snippets:
        pipelineStages:
          - cri: {}
          - json:
              expressions:
                status: status
                request_method: request_method
                http_host: http_host
                server_name: server_name
                upstream_cache_status: upstream_cache_status
                geoip_country_code: geoip_country_code
                scheme: scheme
                request_time: request_time
                upstream_response_time: upstream_response_time
                bytes_sent: bytes_sent
                request_uri: request_uri

          - labels:
              status:
              request_method:
              http_host:
              server_name:
              geoip_country_code:
              upstream_cache_status:
              request_uri:

          - metrics:
              request_duration_seconds:
                type: Histogram
                description: "Request duration in seconds"
                source: request_time
                config:
                  buckets: [0.1, 0.5, 1, 2, 5, 10]
          - drop:
              source: request_uri
              expression: "/(robots.txt|favicon.ico)"

      # 🟣 ATTENTION : scrapeConfigs → extraScrapeConfigs
      extraScrapeConfigs:
        - job_name: kubernetes-pods-nginx
          kubernetes_sd_configs:
            - role: pod

          relabel_configs:
            # Garder uniquement les pods nginx
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: nginx
              action: keep

            # Labels Kubernetes utiles
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
            - source_labels: [__meta_kubernetes_pod_label_app]
              target_label: app
            - source_labels: [__meta_kubernetes_pod_node_name]
              target_label: node

            # Chemin des logs CRI
            - source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              separator: /
              target_label: __path__
              replacement: /var/log/pods/*$1/*.log

    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
