apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: loki
spec:
  dependsOn:
    - name: loki
      namespace: loki
  interval: 12h
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: promtail
      version: "6.15.5"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: loki
      interval: 12h
  values:
    # Configuration complète de Promtail
    config:
      server:
        http_listen_port: 3101
        grpc_listen_port: 0
      
      positions:
        filename: /run/promtail/positions.yaml
      
      clients:
        - url: http://loki:3100/loki/api/v1/push
      
      scrape_configs:
        # Configuration pour tous les pods (par défaut)
        - job_name: kubernetes-pods
          pipeline_stages:
            - cri: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_controller_name
              regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
              action: replace
              target_label: __tmp_controller_name
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
                - __tmp_controller_name
                - __meta_kubernetes_pod_name
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: app
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                - __meta_kubernetes_pod_label_instance
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: instance
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_component
                - __meta_kubernetes_pod_label_component
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: component
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
              - namespace
              - app
              target_label: job
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
              target_label: __path__

        # Configuration spécialisée pour nginx avec parsing JSON
        - job_name: nginx-glefer
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - glefer
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              action: keep
              regex: nginx
            - source_labels: [__meta_kubernetes_pod_container_name]
              action: keep
              regex: nginx
            - source_labels: [__meta_kubernetes_pod_container_name]
              action: replace
              target_label: container
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
              target_label: __path__
              separator: /
              replacement: /var/log/pods/*$1/*.log
          pipeline_stages:
            # Parse JSON logs nginx
            - json:
                expressions:
                  timestamp: timestamp
                  remote_addr: remote_addr
                  method: method
                  uri: uri
                  status: status
                  bytes_sent: bytes_sent
                  request_time: request_time
                  referrer: referrer
                  user_agent: user_agent
            # Labels pour Loki
            - labels:
                method:
                status:
            # Classification des status codes
            - template:
                source: status_class
                template: |
                  {{- if and (ge (int .status) 200) (lt (int .status) 300) -}}2xx
                  {{- else if and (ge (int .status) 300) (lt (int .status) 400) -}}3xx
                  {{- else if and (ge (int .status) 400) (lt (int .status) 500) -}}4xx
                  {{- else if and (ge (int .status) 500) (lt (int .status) 600) -}}5xx
                  {{- else -}}other{{- end -}}
            # Ajout du label status_class
            - labels:
                status_class:
            # Métriques Prometheus dérivées des logs
            - metrics:
                nginx_http_requests_total:
                  type: Counter
                  description: "Total number of HTTP requests by status code"
                  config:
                    value: "1"
                    action: inc
                nginx_http_request_duration_seconds:
                  type: Histogram
                  description: "HTTP request duration in seconds"
                  source: request_time
                  config:
                    buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]

    # DaemonSet pour collecter sur tous les noeuds
    daemonset:
      enabled: true
    
    # Configuration des volumes pour le fichier positions
    extraVolumes:
      - name: positions
        hostPath:
          path: /var/lib/promtail-positions
          type: DirectoryOrCreate
    
    extraVolumeMounts:
      - name: positions
        mountPath: /run/promtail
        readOnly: false
    
    # Service Monitor pour Prometheus
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack