apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: loki
spec:
  dependsOn:
    - name: loki
      namespace: loki
  interval: 12h
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: promtail
      version: "6.15.5"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: loki
      interval: 12h
  values:
    # Utilisation d'un ConfigMap externe pour la configuration complète
    configFrom:
      name: promtail-config
      key: promtail.yaml

    # DaemonSet pour collecter sur tous les noeuds
    daemonset:
      enabled: true
    
    # Configuration des volumes pour le fichier positions
    extraVolumes:
      - name: positions
        hostPath:
          path: /var/lib/promtail-positions
          type: DirectoryOrCreate
    
    extraVolumeMounts:
      - name: positions
        mountPath: /run/promtail
        readOnly: false
    
    # Service Monitor pour Prometheus
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack