apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: glefer-cv
  namespace: glefer
spec:
  imageRepositoryRef:
    name: glefer-cv
  policy:
    latest: {}
  filterTags:
    pattern: '^sha-main-[a-f0-9]+'
    extract: '$0'